CREATE TABLE `campgrounds` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`title` TEXT NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`price` DECIMAL(20,2) NOT NULL DEFAULT '0.00',
	`description` LONGTEXT NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`location` TEXT NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=202
;